# gcp_distributed.conf
# Configuración para despliegue distribuido en GCP

SSH_USER="Kase"

# IP Pública de la VM de Frontend
FRONTEND_IP="PASTE_PUBLIC_IP_HERE"

# IP Interna de la VM de Backend
BACKEND_INTERNAL_IP="PASTE_INTERNAL_IP_HERE"
