# nodos.conf
# Configuración consolidada para despliegue en una sola VM (Monolito)

# Usuario administrador de la VM
SSH_USER="Kase"

# IP de la VM única (Cambiar por la IP de tu VM local o la IP interna de GCP)
TARGET_IP="134.70.86.38"
